spring.datasource.username=sa
spring.datasource.password=COLOQUE_A_SENHA_LOCAL_AQUI
app.local.database.host=localhost
app.local.database.port=1433
app.local.database.name=StudyConnect
spring.jpa.hibernate.ddl-auto=update
app.security.jwt.secret=GERAR_UMA_CHAVE_BASE64_DE_PELO_MENOS_32_BYTES
